"""
Scripts/outbound_diligence_prospector.py
========================================
Autonomous Outbound Due-Diligence & B2B Prospecting Engine.
Generates tailored 1-page executive risk alerts and personalized outreach
dossiers for compliance directors, maritime trade brokers, and risk analysts.
"""

import sys
import json
import time
from pathlib import Path
from typing import Dict, Any, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DATA_DIR = PROJECT_ROOT / "Data"
OUTBOUND_DIR = PROJECT_ROOT / "Project" / "outbound_prospects"
OUTBOUND_DIR.mkdir(parents=True, exist_ok=True)

PROSPECT_SEGMENTS = [
    {
        "segment_id": "SEG-MARITIME-SG",
        "industry": "Maritime Trade & Bunkering Compliance",
        "region": "Singapore / Malacca Strait Corridor",
        "target_titles": ["Chief Compliance Officer", "Head of Vessel Operations", "Sanctions Screening Director"],
        "pain_point": "Dark fleet oil transfers, aviation fuel transshipments, and sanctions liability under EU/OFAC maritime directives.",
        "sample_target": "IND-MAF-001 (Tun Aung / Air Force Fuel Supply Logistics)"
    },
    {
        "segment_id": "SEG-SUPPLY-CHAIN-TH",
        "industry": "Cross-Border Logistics & Infrastructure",
        "region": "Bangkok / Mae Sot / Myawaddy Border Trade",
        "target_titles": ["VP Supply Chain Risk", "Regional Trade Counsel", "Cross-Border Logistics Director"],
        "pain_point": "Customs blackouts, EAO-controlled toll gates, and supply chain disruptions along the Asian Highway (AH1).",
        "sample_target": "IND-SAC-002 (Soe Win / Ground Forces Logistics & Clearance)"
    },
    {
        "segment_id": "SEG-LEGAL-ESG-UK",
        "industry": "International Human Rights Litigation & ESG Risk",
        "region": "London / Geneva / The Hague",
        "target_titles": ["Senior Sanctions Counsel", "Lead Legal Investigator", "ESG Geopolitical Risk Director"],
        "pain_point": "Universal jurisdiction filings, evidentiary verification for ICJ/ICC proceedings, and supply chain audit trails.",
        "sample_target": "IND-SAC-001 (Min Aung Hlaing / Supreme Command Dossier)"
    }
]


def generate_executive_sample_alert(segment: Dict[str, Any]) -> str:
    """Generates an impactful, personalized 1-page due-diligence sample brief."""
    timestamp = "2026-10-02"
    brief = f"""# EXECUTIVE DUE-DILIGENCE RISK ALERT // CONFIDENTIAL
**Transmitted by:** Parla Autonomous Intelligence Node (`SECTOR-SEA-2026`)  
**Target Sector:** {segment['industry']} ({segment['region']})  
**Date of Assessment:** {timestamp}  
**Classification:** B2B PRELIMINARY AUDIT // EVIDENCE GRADE A1  

---

### 1. Executive Threat Overview
Our autonomous conflict telemetry node has registered elevated regulatory and supply-chain exposure impacting operations across Southeast Asian transit corridors:
* **Active Exposure Vector:** {segment['pain_point']}
* **Primary Cross-Referenced Target:** `{segment['sample_target']}`
* **Statutory Mandate Trigger:** UN Human Rights Council A/HRC/39/64 & US OFAC Executive Order 14014.

### 2. Operational Impact & Compliance Liabilities
Operating entities transacting directly or indirectly through affected logistics nodes face severe strict-liability penalties:
1. **Asset Freezes & Banking Blacklists:** Secondary sanctions exposure on USD/EUR clearing accounts for entities transacting with designated command conglomerates (MEHL / MEC).
2. **Maritime Seizure / De-Flagging Risk:** Vessels linked to unverified bunkering or aviation fuel imports into Myanmar terminals face immediate P&I club insurance cancellation.
3. **Court-Admissible Evidence Logging:** Independent Mechanisms (IIMM) actively archive Merkle-sealed transaction records for international litigation under Rome Statute Article 28.

### 3. Verification & Autonomous Clearance Portal
You can verify your specific bills of lading, corporate counterparties, and regional directors in real-time through our zero-trust search engine:
* **Self-Service Verification Portal:** `https://parla-diligence.internal` (or local node)
* **On-Demand Certified Dossier:** Complete 10-page evidentiary dossier with SHA-256 Merkle Ledger proof ($75 USD / instant USDT/USDC settlement).
* **Corporate API Ingress:** Programmatic sub-second screening feed for your ERP / TMS platforms.

---
*Generated by Parla Autonomous Operations • Zero-Trust • Offline-First • Cryptographically Sealed*
"""
    return brief


def generate_outbound_pitch_email(segment: Dict[str, Any]) -> str:
    """Creates a high-converting cold email template for compliance officers."""
    return f"""Subject: Urgent Sanctions & Supply-Chain Due-Diligence Alert: {segment['industry']} ({segment['region']})

Dear Compliance Director / Risk Counsel,

I am writing from Parla Autonomous Risk Telemetry to share an urgent preliminary due-diligence alert regarding active sanctions enforcement and supply-chain exposure across Southeast Asian trade corridors.

Our monitoring nodes have documented critical legal and logistics risks directly relevant to {segment['industry'].lower()}:
- Problem: {segment['pain_point']}
- Primary Risk Anchor: {segment['sample_target']}
- Regulatory Exposure: OFAC / EU Council secondary sanctions and maritime insurance withdrawal.

We have generated a complimentary 1-page Executive Risk Brief for your review (attached below).

If your team requires instant, court-admissible counterparty verification or certified due-diligence dossiers with cryptographic Merkle proof, you can query our self-service portal or connect via our direct compliance API:

Portal Access: http://127.0.0.1:8000 (or via secure Cloudflare Tunnel)
Single Certified Dossier: $75 USD (Corporate Card / Instant USDT/USDC settlement)
Developer API Access: $199/month (Sub-second sanctions & PEP screening)

Please let me know if you would like us to run a complimentary preliminary screening on any specific vessel, corporate entity, or border corridor.

Sincerely,

Parla Autonomous Intelligence Operations
Regional Risk & Due-Diligence Unit
"""


def run_outbound_prospecting():
    print("=" * 80)
    print(" PARLA AUTONOMOUS OUTBOUND PROSPECTING & REVENUE DISPATCH")
    print("=" * 80)

    for seg in PROSPECT_SEGMENTS:
        seg_id = seg["segment_id"]
        brief_content = generate_executive_sample_alert(seg)
        email_content = generate_outbound_pitch_email(seg)

        brief_path = OUTBOUND_DIR / f"{seg_id}_executive_alert.md"
        email_path = OUTBOUND_DIR / f"{seg_id}_outbound_pitch.txt"

        brief_path.write_text(brief_content, encoding="utf-8")
        email_path.write_text(email_content, encoding="utf-8")

        print(f"[PASS] Generated Prospecting Package: {seg['industry']}")
        print(f"       Alert Brief:  {brief_path.name}")
        print(f"       Outreach Pitch: {email_path.name}")

    print("\n[PASS] All 3 corporate prospect packages ready in: Project/outbound_prospects/")


if __name__ == "__main__":
    run_outbound_prospecting()
